name: SHAD-JUR
channels:
  - conda-forge
dependencies:
  - black=21.10b0
  - matplotlib=3.4.3
  - numpy=1.21.3
  - openpyxl=3.0.9
  - pandas=1.3.4
  - pip=21.3.1
  - python=3.9.7
  - seaborn=0.11.2
  - pip:
    - japanize-matplotlib==1.1.3